export * from './app/app.component';
export * from './top-menu/top-menu.component';
export * from './home/home.component';
export * from './courses/courses.component';
export * from './course-detail/course-detail.component';
export * from './course-list/course-list.component';
export * from './side-menu/side-menu.component';
export * from './course/course.component';
export * from './launch-dialog/launch-dialog.component';
